[package]
name = "lex-babel"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
lex-parser = { path = "../lex-parser" }
comrak = "0.29"

[dev-dependencies]
insta = { workspace = true }
